print("Written by: Javohir")
print("Title: The boy who cried wolf")
print("Setting:movies ")
print("Characters : Batman and Superman")
print("City: NYC")
print("State:NY")
print("Country : United States of World")
print("Continent: America")
print("Planet:Earth")
print(" Galaxy : Milky Way, The End !!!")
