print("Written by: Javohir, Sajed and Anthony")
print("Title: The boy who cried wolf")
print("Setting:movies ")
print("Characters : Batman and Superman")
print("City: NYC")
print("State:NY")
print("Country : United States of World")
